project_identifier: ezplatform-dev
files:
  - source: /**/*.xlf
    translation: >-
      /translations/%locale_with_underscore%/**/%file_name%.%locale_with_underscore%.%file_extension%
    languages_mapping:
      locale:
        en-US: en_US
        pl: pl
        de: de
        el: el
        es: es
        fi: fi
        fr: fr
        hi: hi
        hr: hr
        hu: hu
        it: it
        ja: ja
        nb: nb
        no: no
        nl: nl
        pt-PT: pt
        ru: ru
        zh-HK: zh_HK
    ignore:
      - /translations
      - /bin
      - /docs
